# system config
mode: 0
distribute: True
num_parallel_workers: 8
val_while_train: True
val_interval: 1

# dataset config
dataset: 'mnist'
data_dir: './mnist/'
num_classes: 10
shuffle: True
dataset_download: False
batch_size: 64
drop_remainder: True

# Augmentation config
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
interpolation: 'bicubic'
auto_augment: 'randaug-m7-mstd0.5-inc1'
re_prob: 0.1
mixup: 0.2
cutmix: 1.0
cutmix_prob: 1.0
crop_pct: 0.9
color_jitter: 0.4

# model config
model: 'coat_lite_tiny'
num_classes: 1000
pretrained: False
ckpt_path: ''
keep_checkpoint_max: 10
ckpt_save_policy: 'top_k'
ckpt_save_dir: './ckpt/'
epoch_size: 600
dataset_sink_mode: True
amp_level: 'O2'

# loss config
loss: 'CE'
label_smoothing: 0.1

# lr scheduler config
scheduler: 'warmup_cosine_decay'
lr: 0.00072
min_lr: 0.000005
warmup_epochs: 10
decay_epochs: 290
num_cycles: 2
cycle_decay: 1.0

# optimizer config
opt: 'adamw'
weight_decay: 0.025
filter_bias_and_bn: True
loss_scale: 1024
use_nesterov: False
